name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        projects: [ "ApiLib", "LibrApi" ]
        tests_projects: [ "LibrApi.Tests", "ApiLib.Tests" ]
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for ${{ matrix.projects }}
      run: dotnet restore ./${{ matrix.projects }}/${{ matrix.projects }}.csproj

    - name: Build ${{ matrix.projects }}
      run: dotnet build ./${{ matrix.projects }}/${{ matrix.projects }}.csproj --configuration Release --no-restore

    - name: Test ${{ matrix.tests_projects }}
      run: dotnet test ./${{ matrix.tests_projects }}/${{ matrix.tests_projects }}.csproj --configuration Release --no-build --logger trx
