name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        projects: [ "ApiLib", "LibrApi" ]
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for ${{ matrix.projects }}
      run: dotnet restore ./LibrApi/${{ matrix.projects }}/${{ matrix.projects }}.csproj

    - name: Build ${{ matrix.projects }}
      run: dotnet build ./LibrApi/${{ matrix.projects }}/${{ matrix.projects }}.csproj --configuration Release --no-restore